USE [master]
GO
/****** Object:  Database [Lms]    Script Date: 5/5/2021 5:17:42 AM ******/
CREATE DATABASE [Lms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lms', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Lms.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Lms_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Lms_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Lms] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Lms] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Lms] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Lms] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Lms] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Lms] SET ARITHABORT OFF 
GO
ALTER DATABASE [Lms] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Lms] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Lms] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Lms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Lms] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Lms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Lms] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Lms] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Lms] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Lms] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Lms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Lms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Lms] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Lms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Lms] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Lms] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Lms] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Lms] SET RECOVERY FULL 
GO
ALTER DATABASE [Lms] SET  MULTI_USER 
GO
ALTER DATABASE [Lms] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Lms] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Lms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Lms] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Lms] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Lms', N'ON'
GO
USE [Lms]
GO
/****** Object:  Table [dbo].[Ads]    Script Date: 5/5/2021 5:17:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ads](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[Link] [nvarchar](max) NULL,
	[CreateDate] [date] NOT NULL,
 CONSTRAINT [PK_Ads] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 5/5/2021 5:17:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[IsAdmin] [bit] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Lms] SET  READ_WRITE 
GO
